//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Translator/asm.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="asmParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IasmListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] asmParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] asmParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] asmParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] asmParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] asmParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] asmParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.cInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCInstruction([NotNull] asmParser.CInstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.cInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCInstruction([NotNull] asmParser.CInstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.aInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAInstruction([NotNull] asmParser.AInstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.aInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAInstruction([NotNull] asmParser.AInstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDest([NotNull] asmParser.DestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDest([NotNull] asmParser.DestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump([NotNull] asmParser.JumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump([NotNull] asmParser.JumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="asmParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp([NotNull] asmParser.CompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="asmParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp([NotNull] asmParser.CompContext context);
}
